apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5f53
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5f53
    app.kubernetes.io/part-of: ci1t-43256-0071-app
  name: devfile-sample-5f53
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-5f53
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-5f53
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0071-tenant/ci1t-43256-0071-app/devfile-sample-5f53@sha256:7ceef19c05588b77853324a29723b25a628ba81355c34336d0b8cdb5309dd38e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
